<?php
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Methods: GET, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With");
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(200); exit; }
require_once 'config/database.php';
function send_json($data, int $statusCode = 200): void { http_response_code($statusCode); $json = json_encode($data, JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE); if ($json === false) { http_response_code(500); echo json_encode(['success'=>false,'error'=>'Falha ao gerar JSON','json_error'=>json_last_error_msg()], JSON_UNESCAPED_UNICODE); exit; } echo $json; exit; }
function resolve_period(string $period): array { $period=strtolower(trim($period)); $today=new DateTime('today'); $tomorrow=(clone $today)->modify('+1 day'); switch($period){ case 'today': case 'hoje': return ['key'=>'today','label'=>'Hoje','start'=>$today->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; case '30': case '30d': return ['key'=>'30d','label'=>'30 dias','start'=>(new DateTime('-29 days'))->setTime(0,0,0)->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; case '90': case '90d': return ['key'=>'90d','label'=>'90 dias','start'=>(new DateTime('-89 days'))->setTime(0,0,0)->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; case 'month': case 'mes': return ['key'=>'month','label'=>'Este mês','start'=>(new DateTime('first day of this month'))->setTime(0,0,0)->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; case '7': case '7d': default: return ['key'=>'7d','label'=>'7 dias','start'=>(new DateTime('-6 days'))->setTime(0,0,0)->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; } }
try {
  $store_id = isset($_GET['store_id']) ? (int)$_GET['store_id'] : 0; if ($store_id <= 0) send_json(['success'=>false,'error'=>'ID da loja não fornecido ou inválido.'],400);
  $period = resolve_period((string)($_GET['period'] ?? ($_GET['days'] ?? '7d')));
  $nonSub = "(o.tipo IS NULL OR LOWER(COALESCE(o.tipo,'')) <> 'sub')";
  $response = ['period'=>$period['key'],'periodLabel'=>$period['label'],'startDate'=>$period['start'],'endDate'=>$period['end']];
  $stmt=$pdo->prepare("SELECT COUNT(*) as count FROM orders o WHERE o.store_id=? AND {$nonSub} AND o.created_at>=? AND o.created_at<?"); $stmt->execute([$store_id,$period['start'],$period['end']]); $response['totalOrders']=(int)($stmt->fetch(PDO::FETCH_ASSOC)['count']??0);
  $stmt=$pdo->prepare("SELECT COUNT(*) as count FROM orders o WHERE o.store_id=? AND {$nonSub} AND LOWER(COALESCE(o.status,''))='paid' AND o.created_at>=? AND o.created_at<?"); $stmt->execute([$store_id,$period['start'],$period['end']]); $paidCount=(int)($stmt->fetch(PDO::FETCH_ASSOC)['count']??0); $response['totalSales']=$paidCount; $response['paidOrders']=$paidCount;
  $stmt=$pdo->prepare("SELECT COUNT(*) as count FROM orders o WHERE o.store_id=? AND {$nonSub} AND LOWER(COALESCE(o.status,''))='pending' AND o.created_at>=? AND o.created_at<?"); $stmt->execute([$store_id,$period['start'],$period['end']]); $response['openOrders']=(int)($stmt->fetch(PDO::FETCH_ASSOC)['count']??0);
  $stmt=$pdo->prepare("SELECT COALESCE(SUM(o.total_amount),0) as total FROM orders o WHERE o.store_id=? AND {$nonSub} AND LOWER(COALESCE(o.status,''))='paid' AND o.created_at>=? AND o.created_at<?"); $stmt->execute([$store_id,$period['start'],$period['end']]); $response['revenue']=(float)($stmt->fetch(PDO::FETCH_ASSOC)['total']??0);
  $stmt=$pdo->prepare("SELECT COUNT(*) as count FROM orders o WHERE o.store_id=? AND {$nonSub} AND DATE(o.created_at)=CURDATE()"); $stmt->execute([$store_id]); $response['todayOrders']=(int)($stmt->fetch(PDO::FETCH_ASSOC)['count']??0);
  $stmt=$pdo->prepare("SELECT DATE(o.created_at) as date, SUM(CASE WHEN LOWER(COALESCE(o.status,''))='paid' THEN o.total_amount ELSE 0 END) as total, COUNT(*) as orders, SUM(CASE WHEN LOWER(COALESCE(o.status,''))='paid' THEN 1 ELSE 0 END) as paid_orders, SUM(CASE WHEN LOWER(COALESCE(o.status,''))='pending' THEN 1 ELSE 0 END) as pending_orders FROM orders o WHERE o.store_id=? AND {$nonSub} AND o.created_at>=? AND o.created_at<? GROUP BY DATE(o.created_at) ORDER BY date ASC"); $stmt->execute([$store_id,$period['start'],$period['end']]); $response['chartData']=$stmt->fetchAll(PDO::FETCH_ASSOC);
  $stmt=$pdo->prepare("SELECT p.id,p.name,COALESCE((SELECT pi.image_url FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.image_order ASC, pi.id ASC LIMIT 1), p.mainImage, '') as image, SUM(oi.quantity) as totalSold, SUM(oi.price * oi.quantity) as revenue FROM order_items oi JOIN orders o ON oi.order_id=o.id JOIN products p ON oi.product_id=p.id WHERE o.store_id=? AND {$nonSub} AND LOWER(COALESCE(o.status,''))='paid' AND o.created_at>=? AND o.created_at<? GROUP BY p.id,p.name,p.mainImage ORDER BY totalSold DESC, revenue DESC LIMIT 5"); $stmt->execute([$store_id,$period['start'],$period['end']]); $response['topProducts']=$stmt->fetchAll(PDO::FETCH_ASSOC);
  $stmt=$pdo->prepare("SELECT o.id,o.customer_id,c.name as customer_name,o.total_amount,o.status,o.created_at FROM orders o LEFT JOIN customers c ON o.customer_id=c.id WHERE o.store_id=? AND {$nonSub} AND o.created_at>=? AND o.created_at<? ORDER BY o.created_at DESC LIMIT 5"); $stmt->execute([$store_id,$period['start'],$period['end']]); $response['recentOrders']=$stmt->fetchAll(PDO::FETCH_ASSOC);
  send_json($response,200);
} catch (Throwable $e) { send_json(['success'=>false,'error'=>$e->getMessage()],500); }
?>
