<?php
header("Access-Control-Allow-Origin: *");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Methods: GET, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With");
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(200); exit; }
require_once 'config/database.php';
function resolve_period(string $period): array { $period=strtolower(trim($period)); $today=new DateTime('today'); $tomorrow=(clone $today)->modify('+1 day'); switch($period){ case 'today': case 'hoje': return ['key'=>'today','label'=>'Hoje','start'=>$today->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; case '30d': case '30': return ['key'=>'30d','label'=>'Últimos 30 dias','start'=>(new DateTime('-29 days'))->setTime(0,0,0)->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; case 'month': case 'mes': return ['key'=>'month','label'=>'Este mês','start'=>(new DateTime('first day of this month'))->setTime(0,0,0)->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; case '7d': default: return ['key'=>'7d','label'=>'Últimos 7 dias','start'=>(new DateTime('-6 days'))->setTime(0,0,0)->format('Y-m-d H:i:s'),'end'=>$tomorrow->format('Y-m-d H:i:s')]; } }
try {
  $store_id=isset($_GET['store_id'])?(int)$_GET['store_id']:0; if($store_id<=0) throw new Exception('ID da loja não fornecido.');
  $period=resolve_period((string)($_GET['period']??'30d')); $channel=strtolower(trim((string)($_GET['channel']??'all'))); $whereChannel=''; $params=[$store_id,$period['start'],$period['end']]; $nonSub="(o.tipo IS NULL OR LOWER(COALESCE(o.tipo,'')) <> 'sub')";
  if($channel==='store'){ $whereChannel=" AND LOWER(COALESCE(o.sales_channel,'')) IN ('store','loja','loja_direta','direct') "; } elseif($channel==='marketplace'){ $whereChannel=" AND LOWER(COALESCE(o.sales_channel,'')) IN ('marketplace','ml','mercado_livre','amazon','shopee','magalu','shein','aliexpress') "; }
  $response=['period'=>$period['key'],'periodLabel'=>$period['label'],'channel'=>$channel,'kpis'=>['revenue'=>0,'orders'=>0,'averageTicket'=>0,'conversion'=>0],'dailyRevenue'=>[],'dailyOrders'=>[],'topProducts'=>[],'lowStock'=>[]];
  $stmt=$pdo->prepare("SELECT COUNT(*) as total_orders, SUM(CASE WHEN LOWER(COALESCE(o.status,''))='paid' THEN 1 ELSE 0 END) as paid_orders, COALESCE(SUM(CASE WHEN LOWER(COALESCE(o.status,''))='paid' THEN o.total_amount ELSE 0 END),0) as revenue FROM orders o WHERE o.store_id=? AND {$nonSub} AND o.created_at>=? AND o.created_at<? {$whereChannel}"); $stmt->execute($params); $row=$stmt->fetch(PDO::FETCH_ASSOC)?:[]; $totalOrders=(int)($row['total_orders']??0); $paidOrders=(int)($row['paid_orders']??0); $revenue=(float)($row['revenue']??0); $response['kpis']=['revenue'=>$revenue,'orders'=>$totalOrders,'averageTicket'=>$totalOrders>0?($revenue/$totalOrders):0,'conversion'=>$totalOrders>0?round(($paidOrders/$totalOrders)*100,2):0,'paidOrders'=>$paidOrders];
  $stmt=$pdo->prepare("SELECT DATE(o.created_at) as ref_date, COALESCE(SUM(CASE WHEN LOWER(COALESCE(o.status,''))='paid' THEN o.total_amount ELSE 0 END),0) as value, COUNT(*) as orders FROM orders o WHERE o.store_id=? AND {$nonSub} AND o.created_at>=? AND o.created_at<? {$whereChannel} GROUP BY DATE(o.created_at) ORDER BY ref_date ASC"); $stmt->execute($params); $rows=$stmt->fetchAll(PDO::FETCH_ASSOC); foreach($rows as $r){ $label=date('d/m', strtotime((string)$r['ref_date'])); $response['dailyRevenue'][]=['day'=>$label,'date'=>$r['ref_date'],'sales'=>(float)$r['value']]; $response['dailyOrders'][]=['day'=>$label,'date'=>$r['ref_date'],'orders'=>(int)$r['orders']]; }
  $stmt=$pdo->prepare("SELECT p.id,p.name,COALESCE((SELECT pi.image_url FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.image_order ASC, pi.id ASC LIMIT 1), p.mainImage, '') as image, SUM(oi.quantity) as totalSold, SUM(oi.price * oi.quantity) as revenue FROM order_items oi JOIN orders o ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id WHERE o.store_id=? AND {$nonSub} AND LOWER(COALESCE(o.status,''))='paid' AND o.created_at>=? AND o.created_at<? {$whereChannel} GROUP BY p.id,p.name,p.mainImage ORDER BY totalSold DESC, revenue DESC LIMIT 10"); $stmt->execute($params); $response['topProducts']=$stmt->fetchAll(PDO::FETCH_ASSOC);
  $stmt=$pdo->prepare("SELECT p.id,p.name,COALESCE((SELECT pi.image_url FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.image_order ASC, pi.id ASC LIMIT 1), p.mainImage, '') as image, COALESCE(SUM(pv.stock),0) as stock, MIN(COALESCE(NULLIF(pv.min_stock_alert,0),2)) as min_stock_alert FROM products p LEFT JOIN product_variations pv ON pv.product_id=p.id WHERE p.store_id=? GROUP BY p.id,p.name,p.mainImage HAVING stock <= min_stock_alert ORDER BY stock ASC, p.name ASC"); $stmt->execute([$store_id]); $response['lowStock']=$stmt->fetchAll(PDO::FETCH_ASSOC);
  echo json_encode($response, JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE);
} catch (Throwable $e) { http_response_code(500); echo json_encode(['error'=>$e->getMessage()], JSON_UNESCAPED_UNICODE); }
?>
