import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { Card, CardContent, CardHeader, CardTitle } from "@/src/components/ui/Card";
import { Button } from "@/src/components/ui/Button";
type PeriodKey = 'today' | '7d' | '30d' | '90d';
const labels: Record<PeriodKey, string> = { today: 'Hoje', '7d': '7 Dias', '30d': '30 Dias', '90d': '90 Dias' };
export function MainChart({ data: apiData, period = '7d', onPeriodChange }: { data?: any[]; period?: PeriodKey; onPeriodChange?: (period: PeriodKey) => void; }) {
  const chartData = apiData?.map(item => ({ name: new Date(item.date).toLocaleDateString('pt-BR', period === 'today' ? { hour: '2-digit', minute: '2-digit' } : { day: '2-digit', month: '2-digit' }), sales: parseFloat(item.total || 0) })) || [];
  return (<Card className="col-span-full lg:col-span-2"><CardHeader className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between pb-8"><div><CardTitle>Visão Geral de Vendas</CardTitle><p className="text-sm text-muted-foreground">Desempenho comercial em tempo real</p></div><div className="flex flex-wrap gap-2">{(['today','7d','30d','90d'] as PeriodKey[]).map((key) => (<Button key={key} variant={period === key ? 'outline' : 'ghost'} size="sm" className="flex-1 sm:flex-none" onClick={() => onPeriodChange?.(key)}>{labels[key]}</Button>))}</div></CardHeader><CardContent><div className="h-[250px] sm:h-[350px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}><defs><linearGradient id="colorSales" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#FF6A00" stopOpacity={0.1}/><stop offset="95%" stopColor="#FF6A00" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--muted))" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 12 }} dy={10}/><YAxis axisLine={false} tickLine={false} tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 12 }} tickFormatter={(value) => `R$${value}`}/><Tooltip contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '12px', boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)' }} itemStyle={{ color: '#FF6A00' }}/><Area type="monotone" dataKey="sales" stroke="#FF6A00" strokeWidth={3} fillOpacity={1} fill="url(#colorSales)" /></AreaChart></ResponsiveContainer></div></CardContent></Card>);
}
